name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
permissions:
  contents: write
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.calendar.full.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
          token: ${{ secrets.METRICS_TOKEN }}
      - name: Most used languages
        uses: StefVuck/Github-Language-Stats@v1.1.0
        with:
          visualization_types: leaderboard
          output_path: stats
          exclude_languages: HTML,CSS
          dark_mode: true
          github_token: ${{ secrets.METRICS_TOKEN }}
